server:
  port: 8080

spring:
  datasource:
    url     : ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty}
  liquibase:
    change-log: db/changelog/changelog.xml
  jpa:
    show-sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  application:
    name: ${SPRING_APPLICATION_NAME:user-service}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: 1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}
    enabled: ${EUREKA_CLIENT_ENABLED:false}

app:
  param:
    verification:
      numberOfAttempts: 3
      blockingTime: 10
      verificationCodeLength: 6